version: '3.1'

services:
  db:
    
    # ищем стабильный образ на dockerhub и копируем его имя, желательно указать версию
    image: postgres:15
    
    # задаем имя контейнера которое мы будем видеть в списке работающих контейнеров
    container_name: my_docker_postgres

    



    # указываем параметры в случае сбоя сервиса, говорим контейнеру перезапускаться в случае отключения
    restart: unless-stopped
    # restart: always

    # пробрасываем порты 
    # с лева порт который будем крутить за пределами контейнера (укажем 54321)
    # с права порт на котором крутится postgres внутри контейнера (обычно это 5432)
    ports:
      - "54321:5432"

    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_USER: soaqa
      POSTGRES_DB: db01
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS: "-A md5"

    # подключаю volume для postgresqlво избежании потери данных
    # папка pg-data-backup должна лежать рядом с файлом
    # docker-compose.yaml или относительно него
    volumes:
      - ./backupdb:/var/lib/postgresql/data


# проверить работает ли docker командой service docker status
# Чтобы запустить данный контейнер необходимо в терминале пройти в то же место где
# лежит файл docker-compose.yaml и запусить команду docker-compose up, но если данный контейнер
# запускаем первый раз то необходимо добавить флаг --build 
# docker-compose up --build
# Если у Вас MacOS на Catalina 10.15.7 то нужно установить Docker-Desktop 15й версии не позже.
# он включает в себя docker-compose