"""empty message

Revision ID: 0aec9c9cbf85
Revises: 
Create Date: 2023-10-17 11:12:16.073553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aec9c9cbf85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_for_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_question', sa.Integer(), nullable=True),
    sa.Column('text_question', sa.String(length=1024), nullable=False),
    sa.Column('text_answer', sa.String(length=1024), nullable=False),
    sa.Column('airdate_question', sa.DateTime(), nullable=False),
    sa.Column('saved_question', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_for_db')
    # ### end Alembic commands ###
