"""empty message

Revision ID: 30f0dd976521
Revises: 
Create Date: 2023-10-17 10:34:13.516969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f0dd976521'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_for_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_question', sa.Integer(), nullable=True),
    sa.Column('text_question', sa.String(length=1024), nullable=False),
    sa.Column('text_answer', sa.String(length=1024), nullable=False),
    sa.Column('created_at_question', sa.DateTime(), nullable=False),
    sa.Column('updated_at_question', sa.DateTime(), nullable=False),
    sa.Column('saved_question', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_for_db')
    # ### end Alembic commands ###
