"""empty message

Revision ID: bb8171243b7e
Revises: 
Create Date: 2023-10-16 18:09:38.302747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8171243b7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_for_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_question', sa.String(length=1024), nullable=False),
    sa.Column('text_answer', sa.String(length=1024), nullable=False),
    sa.Column('pub_question', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text_question')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_for_db')
    # ### end Alembic commands ###
