"""empty message

Revision ID: f809a6018c8c
Revises: bb8171243b7e
Create Date: 2023-10-16 18:45:58.104710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f809a6018c8c'
down_revision = 'bb8171243b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('question_for_db_text_question_key', 'question_for_db', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('question_for_db_text_question_key', 'question_for_db', ['text_question'])
    # ### end Alembic commands ###
